workspace:
  base: /test
  path: oe_paragraphs

services:
  web:
    image: fpfis/php71-build:latest
    environment:
      - DOCUMENT_ROOT=/test/oe_paragraphs
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:
  composer-install:
    group: prepare
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer require --dev webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install
      # Reset permission since installation runs as root. @todo Fix this.
      - chown -R 1000:1000 build/sites/default
      - chmod -R 777 /tmp

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat
