language: php

php:
  - 7.1

sudo: false

mysql:
  database: oe_paragraphs
  username: root
  encoding: utf8

env:
  - TEST_SUITE=^8.5
  - TEST_SUITE=^8.6
  - TEST_SUITE=grumphp

install:
  - test $TEST_SUITE == "grumphp" && composer install || composer require drupal/core:$TEST_SUITE

before_script:
  - DRUPAL_DIR=$(pwd)/build
  - mysql -e 'create database oe_paragraphs'
  - ./vendor/bin/run drupal:site-setup
  - test $TEST_SUITE == "grumphp" || ./vendor/bin/run drupal:site-install
  # Start a web server and wait until it comes online.
  - test $TEST_SUITE == "grumphp" || nohup php -S localhost:8888 --docroot $DRUPAL_DIR > /dev/null 2>&1 &
  - test $TEST_SUITE == "grumphp" || until curl -s localhost:8888; do true; done > /dev/null

script:
  - test $TEST_SUITE != "grumphp" || ./vendor/bin/grumphp run
  - test $TEST_SUITE == "grumphp" || ./vendor/bin/behat

notifications:
  email: false
